### PR TITLE
Allow OG-USA to take general S and J

### PR DESCRIPTION
**Pull request by rickecon**
This PR allows OG-USA to take general S and J. I have tested this on both the steady-state and time path computations for (S=30, J=2) and for (S=80, J=7) and it works perfectly except for the error in the last period resource constraint (1e-03). We think we know what this problem is (nonconvex tax functions) and will remedy it with a different PR.

The steady-state will compute with S=20 and J=1. I assume that fully general S and J would compute if we adjusted our starting values. Most of the changes in this PR were to income.py.

### CODE REVIEW

**Comment by rickecon** [comment]
This PR is in reference to [Issue #230](https://github.com/open-source-economics/OG-USA/issues/230). That issue includes some of the discussion and tinkering.

**Comment by jdebacker** [comment]
I'm concerned about the RC error in the last period.  It looks like the tax functions used are concave - the ETR is constant and the MTRx and MTRy are both concave and only depend on x and y, respectively. I might be misremembering, but I thought we got all RC errors to be tiny with this specification.

A check would be to run through with MTRx and MTRy as constants also.  If that yields a last period RC that is within tolerances, then we know it's the tax functions.  Testing with a small S and J should be quick.

**Comment by rickecon** [comment]
@jdebacker @talumbau , Can either of you two see what is failing in the Travis CI checks of this PR? I can't tell by reading the details. I have checked all the usual suspects like the get_reduced_parameters() function in parameters.py. My suspicion is that I am missing the correct TaxFuncEst_baseline.pkl. In other words, if I have 'age specific':True in my kwargs, then I have to have a TaxFuncEst_baseline.pkl that has age-specific tax functions. My suspicion is that the Travis CI call refers to a tax function that is different from what is saved in the repo. But that is just a guess. Any help on getting this PR to pass Travis CI will be appreciated.

**Comment by rickecon** [comment]
@jdebacker I'll run the test with constant (averaged) tax rates.

**Comment by rickecon** [comment]
I just ran the S=30 and J=2 code with the constant tax rates, and the resource constraint error in the last period is now 5.7e-12. I'll run S=80 and J=7 now to make sure that one works.

**Comment by jdebacker** [comment]
@rickecon I see an error about displaying something. Are any of the "show graph" booleans on?

**Comment by talumbau** [comment]
I took a quick look. At least one error is that the code is attempting to create matplotlib figures during a test. The Travis CI environment is not set up to draw these figures so it gets an error. Does it make sense to modify the code so that you can have a flag that turns on drawing the plots but it is off by default (or the other way around and we can modify the tests)?

**Comment by rickecon** [comment]
@talumbau @jdebacker There it is. I had a plotting Boolean left on in the call to inc.get_e_interp() in the parameters.py file (line 689).

**Comment by rickecon** [comment]
@jdebacker @kerkphil , I just finished testing this code with different specifications of the tax functions from txfunc.py and with S=30 and J=2. The only error I ever got was in run #3 in the table below, in which the ETR was a function of both labor and capital income. All the Euler errors and resource constraints in that run were satisfied except for the last period resource constraint error, which was around 1.0e-03.

| Run | ETR form | MTRx form | MTRy form | specific ages | combine ages |
| :---: | --------- | ----------- | ----------- | ------------- | -------------- |
| 1 | const. avg. | const. avg. | const. avg. | good | good |
| 2 | const. avg. | MTRx(x) | MTRy(y) | good | good |
| 3 | ETR(x,y) | MTRx(x) | MTRy(y) | bad | bad |
| 4 | const. avg. | MTRx(x,y) | MTRy(y) | good | good |
| 5 | const. avg. | MTRx(x) | MTRy(x,y) | good | good |
| 6 | const. avg. | MTRx(x,y) | MTRy(x,y) | good | good |

I take this as validation that this PR is ready to be merged and we just need to implement the new functional form for the tax rate functions such that those functions are monotonically increasing in both labor income and capital income, respectively.

**Pull request merged**
