### PR TITLE
Parallelizing tax function estimation

### PR DESCRIPTION
**Pull request by jdebacker**
This PR uses the `multiprocessing` library to parallelize the estimation of tax functions, allowing functions for multiple years of the budget window to be estimated simultaneously.

### CODE REVIEW

**Comment by jdebacker** [comment]
Confirming that estimation in parallel returns the same results as in serial:

```
In [4]: serial_params = pickle.load(open("TxFuncEst_baseline_serial.pkl","rb"))

In [5]: parallel_params = pickle.load(open("TxFuncEst_baseline_parallel.pkl","rb
   ...: "))

In [8]: np.absolute(serial_params['tfunc_etr_params_S']-parallel_params['tfunc_e
   ...: tr_params_S']).max()
Out[8]: 0.0

In [10]: np.absolute(serial_params['tfunc_mtrx_params_S']-parallel_params['tfunc
    ...: _mtrx_params_S']).max()
Out[10]: 0.0

In [11]: np.absolute(serial_params['tfunc_mtry_params_S']-parallel_params['tfunc
    ...: _mtry_params_S']).max()
Out[11]: 0.0

In [12]: np.absolute(serial_params['tfunc_avginc']-parallel_params['tfunc_avginc
    ...: ']).max()
Out[12]: 0.0

In [13]: np.absolute(serial_params['tfunc_avg_etr']-parallel_params['tfunc_avg_e
    ...: tr']).max()
Out[13]: 0.0

In [14]: np.absolute(serial_params['tfunc_avg_mtrx']-parallel_params['tfunc_avg_
    ...: mtrx']).max()
Out[14]: 0.0

In [15]: np.absolute(serial_params['tfunc_avg_mtry']-parallel_params['tfunc_avg_
    ...: mtry']).max()
Out[15]: 0.0
```

**Comment by hdoupe** [comment]
@jdebacker This looks pretty cool.  What's the difference in run time when estimating the tax functions in parallel?

**Comment by jdebacker** [comment]
@hdoupe On my machine (4 CPUs), it looks to cut run time in half.  But didn't get apples to apples comparison - different processes running outside `txfunc.py` and had to change `time` method from `time.clock()` to `time.time()` since `time.clock()` does not work well with multiple processes (we'll want to update to `time.perf_counter` when moving to Python 3.6).

**Comment by hdoupe** [comment]
That sounds great.  I've been reading some about [dask](https://www.kdnuggets.com/2016/09/introducing-dask-parallel-programming.html).  I think it could be helpful as we are adding parallel processing capabilities to OG-USA.  Dask looks relatively easy to use and is embedded in the pandas/numpy ecosystem.

**Comment by jdebacker** [comment]
@hdoupe Let me know if you have a good dask tutorial you can point me towards.  I've had it recommended before, but struggled figuring out how to use it to make asynchronous parallel calls to a function that needs more than one argument.

But I do think the `multiprocessing` library works well here.  Dask seems really cool for operations on large arrays of data.

**Comment by hdoupe** [comment]
@jdebacker Sure thing.  I'll spend some more time with it and get back to you once I've actually used it.

> But I do think the multiprocessing library works well here. Dask seems really cool for operations on large arrays of data.

I totally agree.  Good work here.  Dask looks like it may be helpful for scheduling more complicated task dependencies.  For example, we need to do tasks A, B, and C.  A and B can run at the same time but C can't run until A finishes.

**Comment by jdebacker** [comment]
@hdoupe Good to know - there is more ability to parallel `txfunc.py`, but there are those cases where you need to wait on some results to update others (e.g. if you split out by age).  Perhaps we'll use dask here in the future.

**Comment by jdebacker** [comment]
@rickecon I think this is ready to go, but take a look and let me know if you have any suggestions.  Thanks!

**Comment by rickecon** [comment]
OK. Will look at this tomorrow @jdebacker .

**Comment by rickecon** [comment]
@jdebacker . I ran the baseline from start to finish. It looks like everything works. I couldn't tell how much the speedup was of the tax function estimation in `txfunc.py` because I interrupted the computation a few times. But it seemed like it ran in a little less than an hour. I think the serial code ran in a little over two hours. I am merging.

**Pull request merged**
