### PR TITLE
Tests for demographics.py

### PR DESCRIPTION
**Pull request by jdebacker**
This PR introduces tests of the `demographics.py` module.  These test:
1. That the population distribution at the end of the time path is the same as in the SS.
2. That the population distribution evolves "smoothly" (i.e., no large jumps from one year to the next).
3. That the population growth rate evolves "smoothly" (i.e., no large jumps from one year to the next).

### CODE REVIEW

**Comment by jdebacker** [comment]
@hdoupe Any idea how to fix this Dask issue causing the failure?  Guessing it has to do with Travis CI using a different (probably newer) version of Dask than I am running locally, because I'm not getting these failures.

**Comment by hdoupe** [comment]
Hmm, that seems about right to me. Where is the `Client` created?

**Comment by jdebacker** [comment]
For these tests, it just takes the default `client=None`

**Comment by hdoupe** [comment]
I dropped the `get` key word from: 
```
# SS.py line 370
    results = compute(*lazy_values, get=dask.multiprocessing.get,
                      num_workers=num_workers, scheduler=client)
```

so that now it's:

```
# SS.py line 370
    results = compute(*lazy_values,
                      num_workers=num_workers, scheduler=client)
```

and that seems to work. It looks like the current behavior is to use processes, but I'm not sure how to specify that from the new API.

**Comment by jdebacker** [comment]
Thanks @hdoupe.  I updated my Dask version and also found that `scheduler=dask.multiprocessing.get` works.  Will update this PR soon - running some tests on another branch now.

**Comment by hdoupe** [comment]
No problem!

**Pull request merged**
