### PR TITLE
Update names of variables constructed from TC data

### PR DESCRIPTION
**Pull request by jdebacker**
This PR addresses Issues #299 by updating the names used for variables constructed from the Tax Calculator data.

### CODE REVIEW

**Comment by jdebacker** [comment]
@andersonfrailey @hdoupe Do you all know what the cause of the Travis CI error is here?  It reads;

```

self = <taxcalc.records.Records object at 0x7f9cb508dc10>
data =       age_head  DSI  EIC  FLPDYR  f2441  f6251  MARS  XTOT   e00200   e00300  ...8798           0    10170         0        0   8798  
[8799 rows x 73 columns]
exact_calculations = False
gfactors = <taxcalc.growfactors.Growfactors object at 0x7f9cb64813d0>
weights =        WT2008       WT2009       WT2010       WT2011       WT2012  \
0     335...11201   446.629696   443.611201   446.629696  32095  
[8799 rows x 20 columns]
adjust_ratios = 'puf_ratios.csv', benefits = None, start_year = 2011
    def __init__(self,
                 data='puf.csv',
                 exact_calculations=False,
                 gfactors=Growfactors(),
                 weights=PUF_WEIGHTS_FILENAME,
                 adjust_ratios=PUF_RATIOS_FILENAME,
                 benefits=None,
                 start_year=PUFCSV_YEAR):
        # pylint: disable=too-many-arguments,too-many-locals
        self.__data_year = start_year
        # read specified data
        self._read_data(data, exact_calculations)
        # check that three sets of split-earnings variables have valid values
        msg = 'expression "{0} == {0}p + {0}s" is not true for every record'
        tol = 0.020001  # handles "%.2f" rounding errors
        if not np.allclose(self.e00200, (self.e00200p + self.e00200s),
                           rtol=0.0, atol=tol):
            raise ValueError(msg.format('e00200'))
        if not np.allclose(self.e00900, (self.e00900p + self.e00900s),
                           rtol=0.0, atol=tol):
            raise ValueError(msg.format('e00900'))
        if not np.allclose(self.e02100, (self.e02100p + self.e02100s),
                           rtol=0.0, atol=tol):
            raise ValueError(msg.format('e02100'))
        # check that ordinary dividends are no less than qualified dividends
        other_dividends = np.maximum(0., self.e00600 - self.e00650)
        if not np.allclose(self.e00600, self.e00650 + other_dividends,
                           rtol=0.0, atol=tol):
            msg = 'expression "e00600 >= e00650" is not true for every record'
            raise ValueError(msg)
        # check that total pension income is no less than taxable pension inc
        nontaxable_pensions = np.maximum(0., self.e01500 - self.e01700)
        if not np.allclose(self.e01500, self.e01700 + nontaxable_pensions,
                           rtol=0.0, atol=tol):
            msg = 'expression "e01500 >= e01700" is not true for every record'
>           raise ValueError(msg)
E           ValueError: expression "e01500 >= e01700" is not true for every record
../../../../miniconda/envs/ospcdyn/lib/python2.7/site-packages/taxcalc/records.py:146: ValueError
```

I'm not getting this when I run the test locally.  Is there something up with the PUF used for the tests on Travis CI?

**Comment by hdoupe** [comment]
It looks like the part causing the problem [was added recently](https://github.com/open-source-economics/Tax-Calculator/commit/e452fe6cedc136888ce4528ed36699473eed4e42). Is this test using test data for the PUF file?

**Comment by andersonfrailey** [comment]
This is due to a small change in the PUF. Last week we changed how pension income is assigned to non-filers and Martin added the corresponding test. It should be solved by using the PUF issued on March 9th (if I accidentally left you off that email, let me know and I'll send it over to you).

**Comment by andersonfrailey** [comment]
We also changed how `e01500` and `e01700` were calculated in the CPS file, but that will be included in the latest version of taxcalc.

**Comment by jdebacker** [comment]
Thanks @hdoupe and @andersonfrailey.  The test passes locally and I'm using the most recent PUF file from @andersonfrailey for that.  

How do I update  the PUF used by Travis CI so that this test passes?

**Comment by hdoupe** [comment]
@jdebacker It looks like you are using the [test data in the file puf91taxdata.csv.gz.](https://github.com/open-source-economics/OG-USA/blob/master/ogusa/tests/test_basic.py#L16-L20)

I'm not sure where this came from or how it could be changed to satisfy the Tax-Calculator requirement.

**Comment by andersonfrailey** [comment]
@martinholmer might be able to help update travis for this.

**Comment by jdebacker** [comment]
@hdoupe That's right - what data do you use to test Tax Calc? The puf91taxdata.csv.gz file is used on Travis CI since we can push it to the repo and it can be shared publicly.

**Comment by hdoupe** [comment]
I think Tax-Calculator uses the CPS data for testing. The puf 91 file was removed some in TC 0.10.0. Could we use the CPS file for testing?

**Comment by jdebacker** [comment]
@hdoupe -- I'll give it a try. Thanks!  Will open another PR for that.

**Comment by jdebacker** [comment]
Note that tests of `txfunc.py` were expanded, but still do not include the most complicated functions.  These tests are involved and will benefit from creating some fake data where the data generating process is known and thus one can verify the parameters returned from estimation match those used to generate the data. 

cc @rickecon

**Pull request merged**
