### PR TITLE
Set path to tax function output

### PR DESCRIPTION
**Pull request by hdoupe**
This PR allows the user to set the path for the tax function estimation output.  A test was added in `test_parameters.py` to test the logic in `parameters.get_parameters`.  

I tried to write a test, `test_file.py`, that checked that output files were written to the correct location.  However, this involved mocking many functions, and this messed up the other tests.  Unless we find a better way to test the file writing behavior, this should be removed from the PR.

### CODE REVIEW

**Comment by hdoupe** [comment]
@jdebacker This PR is ready for review.

**Comment by jdebacker** [comment]
@hdoupe This looks good to me.  Will merge soon - wanting to wait until @rickecon gets some runs done that he's in the middle of first.

**Comment by hdoupe** [comment]
Thanks @jdebacker.  Contingent on passing the the travis tests, this should be good to go.

**Comment by jdebacker** [comment]
@hdoupe these and some other PRs are looking good and I'm on board to merge.  Hesitating because @rickecon  is in the middle of some runs and I think he'll have some changes.

@rickecon Let me know when you are ok with merging these and we can go ahead and do that.  Let's merge these before you add your PRs for fixes you uncovered trying to run TCJA.

**Comment by hdoupe** [comment]
Ok, that sounds good.  The merge order should probably be #323, #327, and then #324.  I think #324 will have some merge conflicts that will need to be resolved.

**Pull request merged**
