### PR TITLE
Update test run

### PR DESCRIPTION
**Pull request by jdebacker**
This PR improves how one can run a quick/test version of OG-USA.  With `test=True` in the keywords passed to the `execute.runner()` function, the full model solution will complete in just a few minutes.

In addition, this PR:
- Removes old, commented code
- Adds another keyword to the `execute.runner()` function that specified if one wants to solve for the time path (as opposed to just the SS of the model).  With this, the function `execute.runner_SS()` is removed, cutting streamlining the code.

### CODE REVIEW

**Comment by jdebacker** [comment]
@PeterDSteinberg I believe this PR will help with being able to run a scaled-down model for quicker debugging.  See Issue #262  

Let me know if this looks good to you and we can merge.

**Comment by PeterDSteinberg** [comment]
@jdebacker I just did `conda env update` on the `taxcalc-dev` environment and installed updated Tax-Calc (master) and this OG-USA  PR branch.  I found the following error when running one of the `py.test` unit tests - Am I missing an environment variable? - The test is not finding a .pkl it needs:

```
$ py.test test_run_ogusa.py
============================================================= test session starts =============================================================
platform darwin -- Python 2.7.13, pytest-3.0.5, py-1.4.31, pluggy-0.4.0
rootdir: /Users/psteinberg/Documents/AEI/OG-USA, inifile: setup.cfg
plugins: django-3.0.0, pep8-1.0.6
collected 1 items

test_run_ogusa.py F

================================================================== FAILURES ===================================================================
____________________________________________________________ test_run_micro_macro _____________________________________________________________

    def test_run_micro_macro():

        reform = {
        2016: {
            '_II_rt1': [.09],
            '_II_rt2': [.135],
            '_II_rt3': [.225],
            '_II_rt4': [.252],
            '_II_rt5': [.297],
            '_II_rt6': [.315],
            '_II_rt7': [0.3564],
        }, }
>       run_micro_macro(reform=reform, user_params={'frisch': 0.44, 'g_y_annual': 0.021}, guid='abc')

test_run_ogusa.py:85:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
test_run_ogusa.py:52: in run_micro_macro
    runner(**kwargs)
../../execute.py:42: in runner
    run_params = ogusa.parameters.get_parameters(test=test, baseline=baseline, guid=guid)
../parameters.py:363: in get_parameters
    dict_params = read_tax_func_estimate(estimate_file, baseline_pckl)
../parameters.py:107: in read_tax_func_estimate
    buf = resource_stream(Requirement.parse('ogusa'), path_in_egg)
/Users/psteinberg/anaconda3/envs/taxcalc-dev/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py:1209: in resource_stream
    self, resource_name
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <pkg_resources.PathMetadata instance at 0x109e05950>, manager = <pkg_resources.ResourceManager instance at 0x109e03c68>
resource_name = 'TxFuncEst_baseline.pkl'

    def get_resource_stream(self, manager, resource_name):
>       return open(self._fn(self.module_path, resource_name), 'rb')
E       IOError: [Errno 2] No such file or directory: '/Users/psteinberg/Documents/AEI/OG-USA/TxFuncEst_baseline.pkl'

/Users/psteinberg/anaconda3/envs/taxcalc-dev/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py:1574: IOError
```

**Comment by jdebacker** [comment]
@PeterDSteinberg The pickle file OG-USA is looking for should be in the OG-USA repo (see [here](https://github.com/open-source-economics/OG-USA/tree/master/Python).  Do you see `TxFuncEst_baseline.pkl` in your OG-USA directory?  How about OG-USA/Python?

**Comment by PeterDSteinberg** [comment]
@jdebacker This looks good to me.

**Pull request merged**
