### PR TITLE
Update for version 0.5.+ conda builds

### PR DESCRIPTION
**Pull request by hdoupe**
This PR updates the path to the `setup.py` file, adds parentheses, and fixes the indentation in `wealthinit.py`. After these changes, I was able to successfully build OG-USA 0.5.10. After reviewing and merging this PR, a new OG-USA release should be created, and I'll give the full conda release process another shot.

### CODE REVIEW

**Comment by jdebacker** [comment]
@hdoupe Looks like a failure when trying to use the `Calculator.increment_year()` method. Has something changed in the latest TC release?  Not sure we've testing OG-USA against 0.20.1...

**Comment by hdoupe** [comment]
Thanks for letting me know. I have no idea why the test started failing now. @martinholmer do you have any thoughts on this?

I changed the test default year to the CPS start year and the regular code defaults to the PUF start year. Does that sound sensible?

**Comment by jdebacker** [comment]
@hdoupe error before was with a weights variable key not being found.  Perhaps the CPS test data called by `test_basic.py` need to be updated?

Are these data even necessary now?  Can't we just use the CPS records constructor in TaxCalc and thus not need these test data in this repo?

**Comment by martinholmer** [comment]
@hdoupe and @jdebacker,  I have no idea what's going on with the OG-USA test failure because you don't provide any info about the failure.  What's the error message?

**Comment by jdebacker** [comment]
@martinholmer @hdoupe Look's like Hank fixed it.  Though I'm still unsure why his fixed worked.

@hdoupe Just to be sure things are ok (in case the test coverage of this issue is not good), would you try to run `./run_examples/run_ogusa_example.py` from this branch?  Once it starts estimating the tax functions, we should be ok and you can kill the process.

**Comment by hdoupe** [comment]
@jdebacker asked: 
> Perhaps the CPS test data called by test_basic.py need to be updated?

I'm not sure about that.

> Are these data even necessary now? Can't we just use the CPS records constructor in TaxCalc and thus not need these test data in this repo?

I think it would be better to use the CPS constructor. Would you like me to go ahead and make that change? 

It looks like the the CPS data and weights paths and 2011 as the records start year were passed to the `Records` class. The CPS data start year is 2014. So, I think there was some type of index error. However, I still have no idea why that is just showing up now. 

I'll run the `run_ogusa_example.py` script and see what happens.

**Comment by hdoupe** [comment]
@martinholmer here's the stacktrace:
```
=================================== FAILURES ===================================
______________________ test_get_micro_data_get_calculator ______________________
self = Index(['SEQUENCE', 'WT2015', 'WT2016', 'WT2017', 'WT2018', 'WT2019', 'WT2020',
       'WT2021', 'WT2022', 'WT2023', 'WT2024', 'WT2025', 'WT2026', 'WT2027'],
      dtype='object')
key = 'WT2012', method = None, tolerance = None
    @Appender(_index_shared_docs['get_loc'])
    def get_loc(self, key, method=None, tolerance=None):
        if method is None:
            if tolerance is not None:
                raise ValueError('tolerance argument only valid if using pad, '
                                 'backfill or nearest lookups')
            try:
>               return self._engine.get_loc(key)
../../../../miniconda/envs/ospcdyn/lib/python3.6/site-packages/pandas/core/indexes/base.py:3063: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
>   ???
pandas/_libs/index.pyx:140: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
>   ???
pandas/_libs/index.pyx:162: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
>   ???
pandas/_libs/hashtable_class_helper.pxi:1492: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
>   ???
E   KeyError: 'WT2012'
pandas/_libs/hashtable_class_helper.pxi:1500: KeyError
During handling of the above exception, another exception occurred:
    def test_get_micro_data_get_calculator():
    
        reform = {
        2017: {
            '_II_rt1': [.09],
            '_II_rt2': [.135],
            '_II_rt3': [.225],
            '_II_rt4': [.252],
            '_II_rt5': [.297],
            '_II_rt6': [.315],
            '_II_rt7': [0.3564],
        }, }
    
        calc = get_calculator(baseline=False, calculator_start_year=2017,
                              reform=reform, data=TAXDATA,
                              weights=WEIGHTS,
>                             records_start_year=RECORDS_START_YEAR)
tests/test_basic.py:193: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../../../miniconda/envs/ospcdyn/lib/python3.6/site-packages/ogusa-0.5.10+4.g33e4388-py3.6.egg/ogusa/get_micro_data.py:81: in get_calculator
    calc1 = Calculator(records=records1, policy=policy1)
../../../../miniconda/envs/ospcdyn/lib/python3.6/site-packages/taxcalc/calculate.py:146: in __init__
    self.__records.increment_year()
../../../../miniconda/envs/ospcdyn/lib/python3.6/site-packages/taxcalc/records.py:253: in increment_year
    self.s006 = self.WT[wt_colname] * 0.01
../../../../miniconda/envs/ospcdyn/lib/python3.6/site-packages/pandas/core/frame.py:2685: in __getitem__
    return self._getitem_column(key)
../../../../miniconda/envs/ospcdyn/lib/python3.6/site-packages/pandas/core/frame.py:2692: in _getitem_column
    return self._get_item_cache(key)
../../../../miniconda/envs/ospcdyn/lib/python3.6/site-packages/pandas/core/generic.py:2486: in _get_item_cache
    values = self._data.get(item)
../../../../miniconda/envs/ospcdyn/lib/python3.6/site-packages/pandas/core/internals.py:4115: in get
    loc = self.items.get_loc(item)
../../../../miniconda/envs/ospcdyn/lib/python3.6/site-packages/pandas/core/indexes/base.py:3065: in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
pandas/_libs/index.pyx:140: in pandas._libs.index.IndexEngine.get_loc
    ???
pandas/_libs/index.pyx:162: in pandas._libs.index.IndexEngine.get_loc
    ???
pandas/_libs/hashtable_class_helper.pxi:1492: in pandas._libs.hashtable.PyObjectHashTable.get_item
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
>   ???
E   KeyError: 'WT2012'
pandas/_libs/hashtable_class_helper.pxi:1500: KeyError
```

It's pretty difficult to decipher, but I think the issue has something to do with an incorrect start year being used.

**Comment by martinholmer** [comment]
@hdoupe said:
>  It's pretty difficult to decipher, but I think the issue has something to do with an incorrect start year being used.

Yes.  This error ` KeyError: 'WT2012'` shows that the test was trying to use the CPS data (which start in 2014) in 2012.  Of course, this doesn't make any sense.

Using the `cps_constructor` fixed this error because it automatically handles all the details for you.

@jdebacker

**Comment by jdebacker** [comment]
@hdoupe asked:

> I think it would be better to use the CPS constructor. Would you like me to go ahead and make that change?

If you have time.  Else open and issue to remind us to do this in the future.  I think it'd be nice to remove those data from the repo if possible.  Thanks!

**Comment by jdebacker** [comment]
Thanks for the fix, @hdoupe !

**Pull request merged**
