### PR TITLE
Richer modeling of gov't spending and transfers

### PR DESCRIPTION
**Pull request by salimfurth**
For policy analysis, one wants to hold government spending constant at "current policy" levels and isolate the change of a specific policy proposal (e.g. a tax cut). Currently, OG-USA sets government purchases (`G`) and transfers (`T_H`) as percentages of GDP. After year `tG1`, `G` is forced up or down to reach the desired debt to output ratio in the long run.

This pull request allows the user to set `baseline_spending=True` in the reform kwargs. Doing so instructs the program to load the saved baseline series for `G` and `T_H`. The former is taken as exogenous for the first `tG1` periods, after which it is released to the familiar debt-ratio closure role. `T_H` remains exogenous in the long run, including the steady state.

The pull request also replaces scalar parameters `alpha_T` and `alpha_G` with vectors `ALPHA_T` and `ALPHA_G` which give a time path of the percent of GDP devoted to transfers or spending in each period. That allows for spending or transfer cuts or increases during the early years (and even late in the case of transfers), although they are somewhat endogenous to GDP.

Users can edit variables `T_shifts` and `G_shifts` in `run_ogusa_serial.py` to add or subtract shares of income from the relevant spending stream.

Finally, this PR fixes an oddity in `TPI.py` described in #272, with confusion between `Y` and `Ynew`. Since Ynew has no recursive function, I replaced `Ynew` with `Y` inside the TPI loop. I also moved the calculation of several complicated parameter vectors outside the loop so that they need not be recalculated each iteration.

### CODE REVIEW

**Comment by jdebacker** [comment]
@salimfurth a couple questions related to growth in the model and how that growth interacts with the baseline `G` and `T_H` series:
1) With population growth, if `T_H` and `G` are fixed, then they are declining per capita?
2) Do `T_H` and `G` series grow with exogenous growth in the labor-augmenting technology? Or do they necessarily become a smaller share of the economy?

I guess in general these two questions can be summarized by asking whether the exogenous `G` and `T_H` series are in stationarized values as other model variables are?  I think the important thing is to get this right in terms of the calibration (e.g. if you took CBO projections of `G` and `T_H`, then you'd want to stationarize them before entering them into the model, right?).

cc @rickecon

**Comment by salimfurth** [comment]
@jdebacker, I'm sorry I wasn't clear. By "constant", I merely meant "the same in each of the model runs". It's not intertemporally constant. cc @rickecon 

There are situations where that wouldn't make sense, such as switching between different year-0 interest rates in the open economy version. 

Does that make sense?

**Comment by jdebacker** [comment]
@salimfurth that does make sense.  Thanks.

**Comment by salimfurth** [comment]
My previous PR (#271) created a failure when `small_open=True` because it referenced `G` before assignment. This PR fixes that error with the addition of lines 774-779 in TPI.py.

**Comment by salimfurth** [comment]
@jdebacker & @rickecon, I corrected a few errors for handling the balanced budget case, as well as verifying (per previous comment) that this fixes the current bug in small_open=True.

**Comment by salimfurth** [comment]
@PeterDSteinberg, can you look at 2 things here that I think are related to PR #275:
1) This PR is failing the test because it can't import post_process.
2) When I try to run the code after this change, it can't locate ogusa.scripts. There appears to be a case mistake; the folder that it created on my system was "Scripts" with a capital "S", but run_ogusa_serial calls for "ogusa.scripts" with a small "s".

**Comment by salimfurth** [comment]
Here's the traceback for the current error:

`==================================== ERRORS ====================================
____________ ERROR collecting Python/ogusa/tests/test_run_ogusa.py _____________
ImportError while importing test module '/home/travis/build/open-source-economics/OG-USA/Python/ogusa/tests/test_run_ogusa.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
ogusa/tests/test_run_ogusa.py:17: in <module>
    import postprocess
E   ImportError: No module named postprocess
============================ pytest-warning summary ============================
WC1 None [pytest] section in setup.cfg files is deprecated, use [tool:pytest] instead.
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
============================== 1 tests deselected ==============================
=========== 1 deselected, 1 pytest-warnings, 1 error in 4.79 seconds ===========
`

**Comment by PeterDSteinberg** [comment]
Hi @salimfurth 

Regarding question 1) above of yours:

The `ImportError` regarding `postprocess` is my fault - that should have been changed in my PR #275 (PR 275 moved `postprocess.py` and made the `scripts` dir.

An easy fix in your PR here for the CI error would be to change in `ogusa/tests/test_run_ogusa.py` line 17:
```
    import postprocess
```
to
```
from ogusa.scripts import postprocess
```

Regarding question 2) of yours above:

That's puzzling to me that it created a `Scripts` dir instead of `scripts` dir.  Follow up questions:
 * On which operating system did you experience that capitalization issue?  (sounds like a Windows-specific problem to me at first glance)
 * Are you referring to a `Scripts` directory in the site-packages directory of your conda environment?  Can you paste the full path of your erroneous `Scripts` dir and mention how you installed OG-USA: a) `python setup.py install`, b) `python setup.py develop`, c) `conda build` / `conda install`?

**Comment by salimfurth** [comment]
Thanks, @PeterDSteinberg. I manually changed the folder name to `scripts`, and the code runs without a problem. I am indeed on a Windows OS, and I used `conda build` to install OG-USA, basically following the path in http://taxcalc.readthedocs.io/en/latest/contributor_guide.html.

**Comment by salimfurth** [comment]
Another question, @PeterDSteinberg: I can't run `post_process.py` anymore because it can't find the `ogusa` module. I know this is somehow related to path variables, but I don't know how to systematically use those.

I tried updating my environment, but `conda env update` raises an exception. I can't copy the traceback, but the last two lines are:

`Conda Env Exception: environment.yml file not found
There is no requirements.txt`

**Comment by jdebacker** [comment]
@salimfurth This looks good to me.  My only complaint is that all these options are making testing more difficult - just so many different variations of the model to run.  But options are good, so I'm merging.

**Pull request merged**
