### PR TITLE
Update tax functional forms to Cobb-Douglas

### PR DESCRIPTION
**Pull request by rickecon**
This PR updates the functional forms for the effective tax rates (ETR), marginal tax rates on labor income (MTRx), and marginal tax rates on capital income (MTRy). The development of this PR is documented in issue #234.

The Cobb-Douglas functional form that we use for estimating ETR, MTRx, and MTRy for each age and year is the following:

This PR also corrects a small error that was causing big problems. The wage (w) and savings (b) arguments were transposed in the tax.MTR_labor() function call in line 392 of household.py.

### CODE REVIEW

**Comment by jdebacker** [comment]
This is a big improvement - allowing the use of flexible tax functions.  I say we merge this PR now, but note that we are not ready to deploy a new OG-USA on Tax Brain until we've done some more testing.  In particular, we need to do some distributional analysis to see that our model represents filers in each bracket.  Fixing any issues there will be a calibration exercise and should be addressed in a separate PR.

**Comment by talumbau** [comment]
@rickecon @jdebacker the solution here is that this file:

```
Python/test_data/puf91taxdata.csv.gz
```

must be updated to what is in Tax-Calculator master.

**Comment by talumbau** [comment]
the idea is that we want to use the latest Tax-Calculator and see if there are problems. The downside is that we have to periodically update this file to keep in sync with what's happening in Tax-Calculator. somewhat burdensome but I think worth it so we know of problems ahead of time.

**Comment by rickecon** [comment]
I cannot find an updated

Python/test_data/puf91taxdata.csv.gz

in the Tax-Calculator master. I just fetched and merged it to my fork a half hour ago.

**Comment by rickecon** [comment]
OK. I think I found it in the <Tax-Calculator/taxcalc/altdata> folder

**Pull request merged**
