### PR TITLE
Small open

### PR DESCRIPTION
**Pull request by salimfurth**
This branch is ready to be tested and reviewed for substance & style.

### CODE REVIEW

**Comment by rickecon** [comment]
@salimfurth . Thanks for your work on this PR. The failed Travis CI check is one that has happened to @jdebacker and me many times. You can see the error on line 727 of the [Travis CI output](https://travis-ci.org/open-source-economics/OG-USA/builds/174591375). It is that you updated the main steady-state `runner_SS()` but did not update the small version from `execute_small.py` that gets used for the testing.

**Comment by salimfurth** [comment]
Do I also need to update execute_large? Are the differences between execute, execute_small, and execute_large explained anywhere?

**Comment by jdebacker** [comment]
No need to update `execute_large.py` - it's no longer used.  You've already changed `execute.py`, which is used for model runs with the full state space and flags for model solution failures.  `execute_small.py` is a test file (hopefully we update to just have `execute.py` in the future, but for now you'll need to update two of the scripts so a tests can pass).

**Comment by salimfurth** [comment]
How does this look, @rickecon and @jdebacker?

**Comment by rickecon** [comment]
@salimfurth . Nice work. I'll try to check this out this weekend.

**Comment by jdebacker** [comment]
@salimfurth, Code looks great.  I ran a test - your branch with `small_open=False` vs OG-USA master in your fork and got identical results.  I would say merge after doing a couple things:
1) Merge in the OG-USA:master, since this PR is a few commits behind.
2) Set the default parameters in `parameters.py` to their values from OG-USA:master (e.g., `S=80`, `lambdas= np.array([0.25, 0.25, 0.2, 0.1, 0.1, 0.09, 0.01])`)

Thanks!

**Comment by salimfurth** [comment]
@jdebacker, how do I merge in the OG-USA:master? That's a new process for me.

**Comment by jdebacker** [comment]
@salimfurth, on your branch, do `git fetch upstream` then `git merge upstream/master`.  This will merge in commits that are in master, but not in your branch.  When you do this, git will prompt you for a commit message.  Type `i' to insert, then type your message (e.g. "syncing to master").  Then his esc  and then `:wq` to save and exit the message. With these changes committed, do one more `push origin small_open` and I'll merge this PR.

**Comment by salimfurth** [comment]
This works creepily well. Should be all set now @jdebacker.

**Comment by jdebacker** [comment]
Thanks @salimfurth.  Merging.

**Comment by rickecon** [comment]
Great work, @salimfurth . This is a great contribution.

**Comment by salimfurth** [comment]
Damn, it feels good to be a gangsta.

One thing worth considering: should small_open:True be the default? We didn't decide before the merge.

**Comment by jdebacker** [comment]
@salimfurth That's a good point.  It's probably something we want to include an option for in the web-app when we decide to update the OG-USA version on TaxBrain.  I'll open an issue now.

**Pull request merged**
