### PR TITLE
CPS capital gains treatment

### PR DESCRIPTION
**Pull request by jdebacker**
This PR applies a temporary fix to impute short and long term capital gains when using CPS data.

The PR also makes a fix so that the `/run_examples/run_ogusa_example.py` script uses the `Records.cps_constructor()` method.

### CODE REVIEW

**Comment by jdebacker** [comment]
@hdoupe I merged PR #364 with the same unit test failure I'm seeing here.  I had to rebase in that PR due to a staged commit with a large datafile.  I was hoping a clean push of the data files used for testing here would help pass this test, but they didn't.   

I don't know why the tests fail on Travis CI, but pass locally.  Could it be with a tolerance on `np.allclose()`?  I haven't specified that anywhere, but perhaps this differs when run on Travis CI?  Other ideas?

**Comment by hdoupe** [comment]
@jdebacker I haven't figured out the error yet, but the warnings look like they are caused by the `sse_mats` array having `NaN` values in it.

I added the print statements in `txfunc.py` lines 558-561:
```
            # plt.show()
        print('sse_mat_new', sse_mat_new)
        print('thresh2', thresh2)
        print('sse_mat > thresh2', sse_mat_new > thresh2)
        print('(sse_mat_new > thresh2).sum() > 0', (sse_mat_new > thresh2).sum() > 0)
        if (sse_mat_new > thresh2).sum() > 0:
            # Mark the outliers from the second sweep above
            sse_mat_new2 = sse_mat_new.copy()
            sse_mat_new2[sse_big_mat] = np.nan
            if graph:
                # Plot sum of squared errors of tax functions over age
                # for each year of budget window
```

and got output:

```
HDoupe-MacBook-Pro:ogusa henrydoupe$ source activate ospcdyn
(ospcdyn) HDoupe-MacBook-Pro:ogusa henrydoupe$ py.test tests/test_txfunc.py::test_find_outliers -s -v -m 'not full_run and not regression' --showlocals
=========================================================================================== test session starts ============================================================================================
platform darwin -- Python 2.7.14, pytest-3.5.0, py-1.5.3, pluggy-0.6.0 -- /anaconda/envs/ospcdyn/bin/python
cachedir: ../.pytest_cache
rootdir: /Users/henrydoupe/Documents/OG-USA, inifile: setup.cfg
collected 2 items                                                                                                                                                                                          

tests/test_txfunc.py::test_find_outliers[2] MTRy :  1  observations tagged as outliers.
MTRy :  After second round,  1  observations tagged as outliers (cumulative).
sse_mat > thresh2 [[21. 22.]
 [20. 32.]
 [20. nan]] 32.1214034008 [[False False]
 [False False]
 [False False]]
PASSED
tests/test_txfunc.py::test_find_outliers[8] MTRy :  0  observations tagged as outliers.
PASSED

============================================================================================= warnings summary =============================================================================================
ogusa/tests/test_txfunc.py::test_find_outliers[2]
  /Users/henrydoupe/Documents/OG-USA/ogusa/txfunc.py:515: RuntimeWarning: invalid value encountered in greater
    thresh2 = (sse_mat_new[sse_mat_new > 0].mean() + se_mult *
  /Users/henrydoupe/Documents/OG-USA/ogusa/txfunc.py:516: RuntimeWarning: invalid value encountered in greater
    sse_mat_new[sse_mat_new > 0].std())
  /Users/henrydoupe/Documents/OG-USA/ogusa/txfunc.py:517: RuntimeWarning: invalid value encountered in greater
    sse_big_mat += sse_mat_new > thresh2
  /Users/henrydoupe/Documents/OG-USA/ogusa/txfunc.py:558: RuntimeWarning: invalid value encountered in greater
    print('sse_mat > thresh2', sse_mat_new, thresh2, sse_mat_new > thresh2)
  /Users/henrydoupe/Documents/OG-USA/ogusa/txfunc.py:559: RuntimeWarning: invalid value encountered in greater
    if (sse_mat_new > thresh2).sum() > 0:

-- Docs: http://doc.pytest.org/en/latest/warnings.html
================================================================================== 2 passed, 5 warnings in 11.48 seconds ===================================================================================
(ospcdyn) HDoupe-MacBook-Pro:ogusa henrydoupe$ 
```

**Comment by jdebacker** [comment]
@hdoupe Thanks for taking a look at this.  I'll remake my environment and look into the `nan` values.  

Unfortunately, I'm running into similar issues [over in the B-Tax repo](https://github.com/open-source-economics/B-Tax/pull/211).

**Comment by jdebacker** [comment]
B-Tax repo issues was from not being consistent with using CPS vs PUF micro data and is not fixed.

The test failure in this PR remains a mystery, but it seems likely that it has something to do with `scipy.optimize()`.  The output I get locally from txfunc.txfunc_est()` (with the inputs used for testing) is:

```
Params =  [ 6.37000261e-22  2.73413298e-03  1.49073835e-08  1.39727771e-02
  2.32796890e-01 -3.69059719e-02  1.00000000e-04 -1.01967001e-01
  3.96030005e-02  1.02987671e-01 -1.30433574e-01  1.00000000e+00]
wsse =  19527.162030362062
obs =  3798
```

The output for the same when run on Travis CI is:
```
Params =  [ 6.37000261e-22  2.73404357e-03  1.34751071e-08  1.31120075e-02
  2.32797205e-01 -3.69059719e-02  1.00000000e-04 -1.01967001e-01
  3.96030037e-02  1.02987671e-01 -1.30433574e-01  1.00000000e+00]
wsse =  19527.16203
obs =  3798
```

The differences are in the 3rd and 4th parameters in the array of estimated parameters.  This could be related to some mix up between the CPS and PUF data because parameters 1 through 4 listed here are scaled by average income levels.  Checking now.

**Comment by jdebacker** [comment]
Ok - it's not differences in data. 

From Travis CI: `Checking Y =  7740.55345221 364739200.934`

From local test: `Checking Y =  7740.553452210688 364739200.9344876`

Do maybe it's what is coming out of `scipy.optimize()`?  

@hdoupe How can I see the version of Scipy used on Travis CI to compare to what I see from `conda list` in my local environment?

**Comment by hdoupe** [comment]
Click the red "x" by the travis icon. Then, you can see the installed versions if you click the down arrow by `conda env update -f environment.yml`.

It looks like travis is using SciPy 1.0.1. My tests ran fine locally with this version.

**Comment by jdebacker** [comment]
@hdoupe Thanks.  

That is same version I'm running locally too - and tests pass.

**Comment by jdebacker** [comment]
The best I can figure is that there is some difference from `scipy.optimize()`.  Inputs appear the same:

Local:
```
Param_init =  [1.         1.         1.         1.         0.39289996 0.25142765
 0.5       ]
mins and shift =  [-0.03690597 -0.101967   -0.13043357]
Data means =  32448.229691163007 8014.5537049564045 0.1249945122665625 704.9127461822012
Tax func type etc =  DEP etr
```

Travis CI:
```
Param_init =  [1.         1.         1.         1.         0.39289996 0.25142765
 0.5       ]
mins and shift =  [-0.03690597 -0.101967   -0.13043357]
Data means =  32448.2296912 8014.55370496 0.124994512267 704.912746182
Tax func type etc =  DEP etr
```

I don't believe there is any randomness in the `L-BFGS-B` optimization algorithm, but there could be differences across platforms in the machine precision.  [This SO thread](https://stackoverflow.com/questions/46043768/same-optimization-code-different-results-on-different-computers) discusses some relevant issues.

Given the potential issues here - can we test functions that rely on optimizers?

**Comment by hdoupe** [comment]
@jdebacker asked
> Given the potential issues here - can we test functions that rely on optimizers? Is there anyway to be sure the types of numeric values (e.g., float vs double) are the same on both platforms?

I'm not really familiar with this type of problem. However, I hope we can find a way to reliably test these types of functions since OG-USA relies heavily on them. I just printed out the types for all of the inputs listed above:

```
# line 835 in txfunc.py
        print('Param_init = ', params_init, np.dtype(params_init[0]))
        print('mins and shift = ', np.array([min_x, min_y, shift]), np.dtype(min_x), np.dtype(min_y), np.dtype(shift))
        print('Data means = ', X.mean(), Y.mean(), txrates.mean(), wgts.mean(), X.dtype, Y.dtype, txrates.dtype)
        print('Tax func type etc = ', tax_func_type, rate_type)
```

and got output:

```
(ospcdyn) HDoupe-MacBook-Pro:ogusa henrydoupe$ py.test tests/test_txfunc.py::test_txfunc_est -v -s
============================================================================================================================ test session starts =============================================================================================================================
platform darwin -- Python 2.7.14, pytest-3.5.0, py-1.5.3, pluggy-0.6.0 -- /anaconda/envs/ospcdyn/bin/python
cachedir: ../.pytest_cache
rootdir: /Users/henrydoupe/Documents/OG-USA, inifile: setup.cfg
collected 1 item                                                                                                                                                                                                                                                             

tests/test_txfunc.py::test_txfunc_est Param_init =  [1.         1.         1.         1.         0.39289996 0.25142765
 0.5       ] float64
mins and shift =  [-0.03690597 -0.101967   -0.13043357] float64 float64 float64
Data means =  32448.2296912 8014.55370496 0.124994512267 704.912746182 float64 float64 float64
Tax func type etc =  DEP etr
PASSED

========================================================================================================================== 1 passed in 7.27 seconds ==========================================================================================================================
(ospcdyn) HDoupe-MacBook-Pro:ogusa henrydoupe$ 
```

It looks like they are all `np.float64` types. However, I have no idea how to control for different levels of precision on different machines.

What do you think about reducing the number of decimals in the dataframe before passing it to the optimize function:

```
    with open(os.path.join(CUR_PATH,
                           'test_io_data/txfunc_est_inputs.pkl'),
              'rb') as f:
        input_tuple = pickle.load(f)
    (_df, s, t, rate_type, output_dir, graph) = input_tuple
    df = _df.round(2) # round all inputs to two decimal places
```

Another option would be to raise the tolerance in the `np.allclose` function to something like `rtol` equal 0.05 or 0.1 (keeping `atol=0`).

**Comment by jdebacker** [comment]
@hdoupe writes:

> I hope we can find a way to reliably test these types of functions since OG-USA relies heavily on them

Me too!

I've had some issues with different platforms and the use of [MKL](https://software.intel.com/en-us/mkl) in the past.  To test if this an issue here, I added the `nomkl` package to `environment.yml`.  I then created a new environment with this, installed OG-USA, and ran `test_txfunc.py`.  Doing this causes `test_txfunc.test_txfunc_est()` to fail locally.  I printed the following input/output:

```
Param_init =  [1.         1.         1.         1.         0.39289996 0.25142765
 0.5       ]
mins and shift =  [-0.03690597 -0.101967   -0.13043357]
Data means =  32448.229691163007 8014.5537049564045 0.1249945122665625 704.9127461822012
Tax func type etc =  DEP etr
Raw param estimates =  [1.00000000e-12 6.87319703e+01 5.92567795e+00 1.14674142e+02]
Params =  [ 6.37000261e-22  2.73404765e-03  1.62463424e-08  1.48147213e-02
  2.32797191e-01 -3.69059719e-02  1.00000000e-04 -1.01967001e-01
  3.96030035e-02  1.02987671e-01 -1.30433574e-01  1.00000000e+00]
wsse =  19527.162030047846
obs =  3798
tax function type =  DEP
Checking Y =  7740.553452210688 364739200.9344876
```

This does not exactly reproduce the results from Travis CI, but it does show that using MKL makes a significant difference and causes the test to fail.  It seems likely that something is different in the implementation of SciPy across these platforms (such as the use of MKL or not) that is causing this test to fail.  However, I don't know a good way to handle this.

**Comment by jdebacker** [comment]
I've now marked `test_txfunc.test_txfunc_est()` to only run on "full runs".  This way it will not fail on Travis CI.  At the moment, I don't know of a better option given the different performance of Scipy on different platforms.

**Pull request merged**
