### PR TITLE
Allow more flexibility with tax functions

### PR DESCRIPTION
**Pull request by jdebacker**
In PR #238, the ability to have tax functions that don't depend on age or tax functions based on analytical mtrs was lost.  This PR restores those abilities.

### CODE REVIEW

**Comment by talumbau** [comment]
@jdebacker can you merge master into this branch and push? that will restart Travis CI with the fix I just merged.

**Comment by talumbau** [comment]
Actually @jdebacker hold on that might not be necessary

**Comment by talumbau** [comment]
actually I do think it's necessary to merge master into your branch and push now. this will give you the right Travis CI settings for your branch

**Comment by jdebacker** [comment]
@TJ - thanks for the quick fix to pass travis CI.  We should parallelize in the future, so we might need to look at this, but good for now!

**Comment by jdebacker** [comment]
model runs well with age specific = True or false.

**Comment by rickecon** [comment]
This looks like it is ready to merge? @jdebacker

**Comment by jdebacker** [comment]
Model runs with analytical = True or false.  @rickecon can you merge if it looks good to you?

**Comment by rickecon** [comment]
@jdebacker. I just went through your tax.py. Looks good. Merging.

**Pull request merged**
