### PR TITLE
Add getting started instructions

### PR DESCRIPTION
**Pull request by asmockler**
Hey!

I just worked through getting everything set up to be able to run OG-USA locally and thought I would drop my steps into the `README` for anyone looking to do the same in the future.

Let me know if you would suggest getting set up in a different way.

@jdebacker @rickecon

### CODE REVIEW

**Comment by jdebacker** [comment]
@asmockler Thanks for updating the instructions!  And happy to see you working in this repo.

It looks like there is a failure related to the connection between OG-USA and [Tax-Calculator](https://github.com/open-source-economics/tax-calculator/) in Travis CI.  I'll look into this and we'll resolve the issue before merging this PR.

**Comment by rickecon** [comment]
:)
@asmockler @jdebacker

**Comment by jdebacker** [comment]
@asmockler PR #359 that was just merged in should fix the test failure you are seeing here.  Please merge in the changes in master to this branch, then I'll merge your PR.  Thanks!

**Comment by jdebacker** [comment]
@asmockler Thanks for the contribution.  Merging now.

**Pull request merged**
