### PR TITLE
Jdebacker new tax funcs

### PR DESCRIPTION
**Pull request by talumbau**
based on #172, uses capital income marginal tax rate calculation based on suggested by @Amy-Xu

### CODE REVIEW

**Comment by talumbau** [comment]
@jdebacker @Amy-Xu this is just one additional commit from Jason's PR. Please have a look at this commit to see what I did:

https://github.com/talumbau/dynamic/commit/7ea046f67b82469611d392026012652e168c2eb7

**Comment by Amy-Xu** [comment]
@jdebacker leaving the decision to you whether to use the absolute value or those income values directly.

**Comment by jdebacker** [comment]
Perfect.  I think we'll use absolute values, but will check the implied
mtrs first.  I should be able to take what you and TJ have done and run
with it.  Thanks!

**Comment by Amy-Xu** [comment]
@talumbau Just a quick note, I just updated my [PR](https://github.com/open-source-economics/Tax-Calculator/pull/497) with a slightly difference income source list. Copy it here:

```
       mtr_valid_income_types = ['e00200p', 'e00900p',
                                  'e00300', 'e23250',
                                  'e01700', 'e02400',
                                  'e00400', 'e00600',
                                  'e00650', 'e22250',
                                  'e01400', 'e02000']

```

So deleted e01500 and replaced e01000 with e22250. FYI

**Comment by jdebacker** [comment]
Thanks Amy.  I'm merging this and will have a PR later where I update the list of capital income items.

**Pull request merged**
